<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<OutputType>Library</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>
	<ItemGroup>
		<WCFMetadata Include="Service References\" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="TShock" Version="6.1.0" />
	</ItemGroup>
</Project>